version: '3'
services:
  frontend:
    build: ./src
    image: "indexphpts:1.0.0"
    environment:
      - DB_PATH=/tmp/data.db
      - FLAG=COMPFEST15{N0t_s0_S3rVer_S1De_Alw4yS_cH3ck_f0r_R0le_7554f10f0763}
    ports:
      - "10011:3000"
