# Use an official Ubuntu 18.04 as a parent image
FROM ubuntu:18.04

# Set the working directory in the container
WORKDIR /usr/src/app

# Install dependencies
RUN apt-get update && \
    apt-get install -y python3.7 python3-pip && \
    python3.7 -m pip install --upgrade pip

# Copy the current directory contents into the container at /usr/src/app
COPY src .

# Install python libraries
RUN python3.7 -m pip install flask ecdsa flask_cors
ENV FLASK_APP=main.py
EXPOSE 5000
CMD [ "flask", "run","--host","0.0.0.0","--port","5000"]